### ISSUE TITLE
Seeing install libsecret-1-dev message even if its installed

### ISSUE THREAD

**Issue by aayush** [iotaledger/trinity-wallet#1630]
### Bug description
With this version trinity-desktop-0.5.1.AppImage  i am seeing libsecret error.
It is asking me to install libsecret-1-dev. I installed it but still seeing this issue.
Someone in discord asked me to check if gnome-keyring is installed. gnome-keyring was installed in my system before i install libsecret-1-dev

### Environment Specs
I am running it on ubuntu 18.04

What build of Trinity are you running? 
trinity-desktop-0.5.1.AppImage

### Steps To Reproduce
Just start that app from terminal.

### Expected behaviour
App should have started, i should have seen authentication screen.

### Actual behaviour
What really happened.

### Errors
<img width="620" alt="Screen Shot 2019-05-27 at 5 17 39 PM" src="https://user-images.githubusercontent.com/181183/58443649-18c5fb80-80a8-11e9-90d1-21c6d724eefc.png">

Attach crash logs or screenshots of error messages if available. Please ensure that these files do not contain any personal information.

**Comment by aayush** [comment]
I was not seeing this error in version 5.0, i switched to 5.1 and seeing this error message

**Comment by rajivshah3** [comment]
~@rihardsgravis do you think #1548 caused this? The only change was in [this commit](https://github.com/atom/node-keytar/commit/95d135533e12d90778f747765870052072674da2)~

**Comment by rajivshah3** [comment]
Ah wait, I think I might know what happened. If you’ve backed up your seeds/Ledger account indexes, could you try resetting the wallet to see if that helps?

**Comment by rajivshah3** [comment]
The app is probably running into an error at launch, but it’s not related to libsecret. When we started showing errors on launch to the user so that they (and we) could see what was actually happening instead of a blank screen, we used a screen that is already used to show error messages to Linux users. This screen would show a specific message if a certain error happened, and the missing dependencies message for all other issues. When we added support for showing the error to the user, there was an issue with the implementation:

https://github.com/iotaledger/trinity-wallet/blob/b77b8145834fda432d4699f145cd2cccd656b401/src/desktop/src/ui/global/FatalError.js#L86

This would cause Windows and macOS users to see the error, but Linux users would see the missing dependencies message for **almost any error**, even ones unrelated to the keychain
