### ISSUE TITLE
Re: Using latest Trinity Desktop with Ledger Nano S

### ISSUE THREAD

**Issue by jiangh77** [iotaledger/trinity-wallet#1694]
I updated to the latest version of Trinity Desktop Wallet

I tried to generate a receiving address in the trinity IOTA wallet
secured by Ledger Nano S

I followed the steps connected Ledger Nano S, went into IOTA App,
click on Receive then generate address in Trinity Wallet, address is
generated but it only flashed for 1 second on the screen and then
disappeared before I can do anything

How can I make the address showing longer on the screen so I can copy it?

Thank you
Have a good week

**Comment by t00k** [comment]
Hello @jiangh77 
This usually happens when the user have not accepted the warning on the Ledger itself.

Wolfgang from the IF posted this in the hardware-wallets channel last week. Try it and see if it works for you;

> If you see the warning for a split second but don't have the chance to confirm it on the Ledger, some program (like Trinity, Ledger Live, Browser) is running and accessing the ledger device, which should not be the case! Close everything and try again! If the message still disappears, you can try the following to be absolutely sure that nothing is interacting with the Ledger:
> - Plug the NanoS into a USB charger, for example for your phone, it can be anything that is not a computer
> - Enter your PIN and then start the IOTA application. You now see “WARNING!”
> - Scroll down. To do so press the right button 5 times until you see “for more info.” and two horizontal lines where the buttons are.
> - Click both buttons on the NanoS at the same time to show “IOTA”

So first make sure that you do not have Ledger Live och Trinity running when plugging in the Ledger. Then make sure to accept the warning on the Ledger itself. Otherwise try the steps provided.

**Comment by jiangh77** [comment]
Thank you, problem solved

Have a good week

**Comment by rihardsgravis** [comment]
Thanks @t00k for the support
