### ISSUE TITLE
use secure enclave for authentication

### ISSUE THREAD

**Issue by javixeneize** [iotaledger/trinity-wallet#1814]
### Description
Delegate login on secure enclave

### Motivation
I have read this (https://blog.iota.org/trinity-threat-modelling-mitigation-report-a1c183eb3970) and its a bit confusing for me. I believe that in iOS a better (and safer) implementation can be done.
### Requirements
Here is a bit of explanation on how to implement that -- https://developer.apple.com/documentation/security/certificate_key_and_trust_services/keys/storing_keys_in_the_secure_enclave

### Am I planning to do it myself with a PR?
Yes :)

**Comment by rajivshah3** [comment]
I believe we looked at this before and found that it’s unfortunately not possible. From my understanding of the documentation, keys that are stored inside the Secure Enclave must be generated inside it. 

“Not having a mechanism to transfer key data into or out of the Secure Enclave is fundamental to its security.”

https://developer.apple.com/documentation/security/certificate_key_and_trust_services/keys/storing_keys_in_the_secure_enclave?language=objc

Unfortunately, we need access to this key data since the Apple APIs do not support IOTA’s signing algorithm

**Comment by cvarley100** [comment]
Unfortunately this is not possible given the current hardware capabilities. We will revisit this and consider alternatives/workarounds for V2 however.
