### ISSUE TITLE
Blank screen after clicking "Settings" on login screen

### ISSUE THREAD

**Issue by luca-moser** [iotaledger/trinity-wallet#1836]
### Bug description
Trinity's app window gets blank after clickong on "Settings" on the login screen.

### Environment Specs
What device are you running Trinity on?

- Manufacturer: Lenovo
- Model: T480
- OS version: Windows 10

- Trinity version: v0.6.1

### Steps To Reproduce
1. download
2. run
3. blank screen

### Expected behaviour
Settings should open.

### Actual behaviour
Blank screen.

**Comment by schadegg** [comment]
Confirm identical behavior while running on Mac OS X (10.14.1). Blank trinity window screen, unresponsive.

**Comment by rajivshah3** [comment]
Which version were you running previously?

**Comment by laumair** [comment]
@luca-moser Did you update to `v0.6.1` from an older version? 

If yes, then this is probably related to https://github.com/iotaledger/trinity-wallet/issues/1815 and https://github.com/iotaledger/trinity-wallet/issues/1753. It's already fixed with https://github.com/iotaledger/trinity-wallet/pull/1832 and will be available in the next version.

**Comment by cvarley100** [comment]
Should be fixed in 1.0.0
