### ISSUE TITLE
ERROR ACCESING TRINITY

### ISSUE THREAD

**Issue by Federico8484** [iotaledger/trinity-wallet#2596]
I download 1.4.2 for desktop windows 10. error migrating data.
I download 1.4.3 for desktop windows 10. same error

I can't access my IOTA. I can't verify if I've been stolen.
Moreover I don't know who to ask. Not customer service in iota web.
And I have to write an ISSUE here. This is not really what someone expects. Not professional at all.

In spanish: Muy **LAMENTABLE**.

[error.pdf](https://github.com/iotaledger/trinity-wallet/files/4242297/error.pdf)

**Comment by t00k** [comment]
Hello Federico.
The migrating error should have been fixed in 1.4.3, please try to run it again using version 1.4.3..
If that is still not possible, the whole migration indicates that you used a VERY old version of Trinity, and should then not be affected of the exploit that came in 1.2.X versions.

Please read https://medium.com/@hbmy289/how-to-check-your-balance-without-using-trinity-e1cac78e97a7 for how to lookup your funds without using Trinity.

Also, beware of scammers lurking around this space. Never share your seed with ANYONE.

If it still doesnt work after trying to migrate again with 1.4.3, please make sure you have your seeds backed up, then reset the wallet. This you can do from Advanced settings.

t00k, Discord Moderator. Not part of IF.

**Comment by Federico8484** [comment]
sorry, I'm not an expert.
The solution you gave is not an option. 
Would you tell to a visa user to reprogram a credit card?
If your bank account would have been hacked, would you accept the director of the bank telling you to start digging in informatic issues. Come on boy, This is not serious. This is not my job man.
I'm just a user. Not an expertise.
 If I had an old version of Trinity and that's the cause, then you (one of the hundreds of developers) should have to reprogram a version 1.4.4. or whatever to fix that. 
Telling me to do what you said in your article is like giving an explanation in chinese to an american user. Not serious . I'm starting thinking this tangle shit you don't know even what you are doing.
This looks like a scam. And your solution a joke.
Well, at least if I had old version I haven't been hacked. Thank you for that. I feel better (irionic mode off)

**Comment by t00k** [comment]
First of all. This isnt a bank, this is crypto.

And I am just a Discord moderator, not a dev. Trying to help you out.

**Comment by Federico8484** [comment]
First of all. I wrote an issue because I couldn't open trinity.
Second of all I already said 1.4.3. Trinity didn't work. 
And you didn't answer my question because you didn't gave me a SOLUTION to enter my trinity wallet. 
Third of all. I ALREADY said there were no customer attention. 
Fourth of all if you are just a moderator what are u doing telling me what to do if apparently as you said you are not a dev?
FINALLY I know this is not a bank but the amount of iota in my trinity cost me 10k euros. 
And I can't even open my account. And you are telling me that you are not a bank. AND I didn't say you were. But your shitty platform has been hacked and you demonstrated that you don't even have a solution. 

IOTA Scam

**Comment by cvarley100** [comment]
Hi @Federico8484. Do you have your seed(s) backed up?

 If you do, simply uninstall the app, reinstall and reenter your seed(s).

**Comment by Federico8484** [comment]
Thank you Cvarley.
That is will I do. That is a good solution
