### ISSUE TITLE
abnormal bundle with 0 iota tx

### ISSUE THREAD

**Issue by sdellava** [iotaledger/trinity-wallet#286]
### Bug description
generating a 0 iota tx with or without a message, the wallet generate a bundle with two tx.

One tx appear to be useless, especially in case of presence of a message.

### Environment Specs
- Trinity version: desktop

### Steps To Reproduce
1. send a 0 IOTA tx to a valid address and check the created bundle.

**Comment by laumair** [comment]
@sdellava Zero value transactions don't have any inputs. If you manual sync or reset your wallet, the next time you sync you won't be able to find those transactions in your wallet. 

The second transaction in the zero value bundle is sent to one of your own addresses so that these transactions show up if you manual sync or reset.

**Comment by laumair** [comment]
We should add this information to [feature docs](https://github.com/iotaledger/trinity-wallet/blob/develop/docs/featureguide/featureguide.md#zero-value-transfers. ).

**Comment by rajivshah3** [comment]
> Since zero value transfers have just outputs and no inputs, the bundle would not have any address from the sender's seed. This leads to a problem where initial sync and manual sync fail to detect these transfers on the tangle (since they do not have any address information from the sender). To overcome this issue, the application always adds a new transfer object to the bundle containing the first address of the sender.

It seems like it's already there

**Comment by sdellava** [comment]
ok. tnx. Clear.
