### ISSUE TITLE
 transaction couldn't reach the required number of confirmations and is now showing invalid balance.

### ISSUE THREAD

**Issue by yumminess** [iotaledger/trinity-wallet#2928]
## Bug description

**The coins left the wallet, and the hash transaction is not successful. The exchanger did not send me anything in return. Invalid balance. The exchanger said that: the amount should return back to your wallet. Since the transaction couldn't reach the required number of confirmations and is now showing invalid balance. the funds should be returned automatically, but they were not returned 

See hash screen please https://thetangle.org/transaction/TQCPDEKHVWLM9XRBGIELJJYKODNYTSGMGMLHEA9CUYUZJUXZVNZSTNKU9VRDPTVJNEZ9ZO9YFBVFA9999**

Please help me
![Screenshot_3](https://user-images.githubusercontent.com/53711708/88851987-43549c80-d1f6-11ea-93fd-c1fdb671c573.jpg)

**Comment by HBMY289** [comment]
There is nothing wrong with this transaction. The bundle was reattached and one of the reattachments was confirmed.
https://thetangle.org/bundle/FHQVZULJGDOHNRIDVJKFAVF9TV9NZACIWJLDOODV9GZOJQXIXU9JJFCSFETVHIHFDAKFVWZLADEJHUZJ9

Other copies of the bundle are now correctly marked with the invalid balance maker as they can not confirm now because the required balance has been moved by the confirmed transaction.

I do not know which exchange this was but they need to train their support better.
This is the confirmed transaction:
https://thetangle.org/transaction/LKZOFMEHNSLBCIWZBKVOBEISKNZ9UMTGOUNIYVLJWJZZTXSTNZSGKNUFUDZJGUOPYHCQNGNCXZI9Z9999

You can send this to their support.
With iota there is now acquired number of confirmations and also no automatic return of funds.
