### ISSUE TITLE
Missing translations in Trinity desktop (crowdin translated to 100%)

### ISSUE THREAD

**Issue by UmbahaSpodPaha** [iotaledger/trinity-wallet#308]
### Bug description
Missing translations (almost all of them are already translated on crowdin for PL lang but not added to Trinity)

### Environment Specs
What device are you running Trinity on?

- Manufacturer: PC
- OS version: Windows 7 x64

What build of Trinity are you running? Please provide the full version (you can find it in Settings > About Trinity).

- Trinity version: 0.3.3

### Missing translation lines:
- "All" (on transaction type selector)
- "BETA version warning: Do not send large amounts with this wallet."
- "Close" (also on TRINITY INFO screen)
- "Drop SeedVault file here or click to browse"
- "Help" -> "Trinity Help" (on menu -> help)
- "Randomise x characters to continue" (BLUE BUTTON on seed generator screen)
- "THEME" and "LABEL" (theme selector)
- "You must save your seed with" ... "of the options listed below." (only center part is translated -> see screenshots)
- Theme names (at least DEFAULT, CLASSIC should be translated (or all))

### Screenshots
![all](https://user-images.githubusercontent.com/35224101/44877129-44e05780-aca3-11e8-80d9-9448a42611ad.png)
![beta version close](https://user-images.githubusercontent.com/35224101/44877131-44e05780-aca3-11e8-8b96-3f550b607431.png)
![drop seedvault](https://user-images.githubusercontent.com/35224101/44877132-4578ee00-aca3-11e8-894a-fd1f809aee11.png)
![help trinity help](https://user-images.githubusercontent.com/35224101/44877133-4578ee00-aca3-11e8-9fb1-fd80a50689ff.png)
![randomise characters](https://user-images.githubusercontent.com/35224101/44877134-4578ee00-aca3-11e8-82be-ae7576c6b810.png)
![theme label](https://user-images.githubusercontent.com/35224101/44877137-4578ee00-aca3-11e8-9be9-55e7a3ec2be8.png)
![themenames](https://user-images.githubusercontent.com/35224101/44877138-4578ee00-aca3-11e8-8a12-41a2422ab2ff.png)
![you must save of the options](https://user-images.githubusercontent.com/35224101/44877139-46118480-aca3-11e8-8e54-00cf99dde940.png)

**Comment by rajivshah3** [comment]
Making the list a checklist:

- [ ] "All" (on transaction type selector)
- [ ] "BETA version warning: Do not send large amounts with this wallet."
- [ ] "Close" (also on TRINITY INFO screen)
- [ ] "Drop SeedVault file here or click to browse"
- [ ] "Help" -> "Trinity Help" (on menu -> help)
- [ ] "Randomise x characters to continue" (BLUE BUTTON on seed generator screen)
- [ ] "THEME" and "LABEL" (theme selector)
- [x] "You must save your seed with" ... "of the options listed below." (only center part is translated -> see screenshots) (bug fixed in #304)
- [ ] Theme names (at least DEFAULT, CLASSIC should be translated (or all))
