### ISSUE TITLE
NSInvalidArgumentException in RNCamera

### ISSUE THREAD

**Issue by rajivshah3** [iotaledger/trinity-wallet#440]
## Error in Trinity Mobile

**NSInvalidArgumentException** in **RNCamera**
*** -[AVCaptureSession addOutput:] Cannot add output <AVCaptureMetadataOutput: 0x2815cf5a0> to capture session <AVCaptureSession: 0x281775a50 [AVCaptureSessionPresetHigh]> because more than one output of the same type is unsupported

[View on Bugsnag](https://app.bugsnag.com/iota-foundation/trinity-mobile/errors/5bab2ce8b9b2590019714ead?event_id=5bb0ed24002fe85c24fc0000&i=gh&m=ci)

## Stacktrace
```
   iotaWallet-[RNCamera _setupOrDisableMetadataOutput]	
   iotaWallet-[RNCamera setupOrDisableBarcodeScanner]	
   iotaWallet-[RNCameraManager set_barCodeScannerEnabled:forView:withDefaultView:]	
   iotaWallet-[RCTComponentData callCustomSetter:onView:withProp:isShadowView:]	
   iotaWallet__49-[RCTComponentData createPropBlock:isShadowView:]_block_invoke_2	
   iotaWallet__37-[RCTComponentData setProps:forView:]_block_invoke	
   iotaWallet-[RCTComponentData setProps:forView:]	
   iotaWallet__50-[RCTUIManager createView:viewName:rootTag:props:]_block_invoke
```

[View full stacktrace](https://app.bugsnag.com/iota-foundation/trinity-mobile/errors/5bab2ce8b9b2590019714ead?event_id=5bb0ed24002fe85c24fc0000&i=gh&m=ci)

*Created by Rajiv Shah via Bugsnag*

**Comment by rajivshah3** [comment]
Related to https://github.com/react-native-community/react-native-camera/issues/1616

**Comment by ashokprogress** [comment]
Fatal Exception: NSInvalidArgumentException*** -[AVCaptureSession addOutput:] Cannot add output <AVCaptureMetadataOutput: 0x1c0637e00> to capture session <AVCaptureSession: 0x1c0013d50 [AVCaptureSessionPresetPhoto]> because more than one output of the same type is unsupported Raw Text
--
0 | CoreFoundation | __exceptionPreprocess
2 | AVFoundation | -[AVCaptureSession addOutput:]
3 | mobile | -[RNCamera _setupOrDisableMetadataOutput]
4 | mobile | -[RNCamera setupOrDisableBarcodeScanner]
5 | mobile | __24-[RNCamera startSession]_block_invoke
6 | libdispatch.dylib | _dispatch_call_block_and_release
13 | libsystem_pthread.dylib | start_wqthread

**Comment by ashokprogress** [comment]
@rajivshah3  any inputs

**Comment by rajivshah3** [comment]
@AshokICreate I'm not sure how to fix this. We're waiting for a fix from `react-native-camera`

**Comment by cvarley100** [comment]
As this is a `react-native-camera` bug, I will close it for now. We can revisit when a fix is released.
