### ISSUE TITLE
Missing translations (crowdin translated to 100%)

### ISSUE THREAD

**Issue by antalm** [iotaledger/trinity-wallet#519]
### Bug description
Missing translations.

### Environment Specs
What device are you running Trinity on?

- Manufacturer: Apple
- Model: iPhone
- OS version: IOS 12.0

What build of Trinity are you running? Please provide the full version (you can find it in Settings > About Trinity).

- Trinity version: 0.5.1

### Missing translations
- "Standard/Advanced" in settings menu Mode always shows Standard/Advanced instead of localized string, however the strings are shown correctly when using the switch to select between Standard and Advanced
- "Mode updated" and "You have changed to Standard/Advanced mode" are not localized, no strings on crowdin
- "Default/Classic/Mint/Electric/etc." theme names are not localized, although translated on crowdin
- "Sending {{ amount }} (= {{ fiat_amount }}) from {{ account_name }} to {{ address }}" is not localized, no string on crowdin (appears when one needs to confirm sending iota to an address)
- Status strings that are displayed above the progress bar during sending iota (like Preparing inputs, completing proof of work, etc.) are not localized
- "Attaching address (counter) / (max number)" is not localized, no string on crowdin (progress indicator during snapshot transition)

**Comment by f-ben** [comment]
On mobile the string on the delete account confirmation page are not completely translated
![image](https://user-images.githubusercontent.com/2088471/47969269-53693780-e075-11e8-8f8b-ef8e88283311.png)

**Comment by f-ben** [comment]
Trinity desktop when adding a ledger-seed
![image](https://user-images.githubusercontent.com/2088471/48306461-6bd7c700-e539-11e8-8b19-74921dfe53b5.png)

**Comment by antalm** [comment]
Although not Trinity Mobile, but I don't want to open a separate one for this minor issue.
On the top left of the transaction history there's a filter (all/sent/received/pending/hide zero value). The "All" string (on the picture see "All (121)") is not translated.
![trinity_filter_all](https://user-images.githubusercontent.com/29548853/48870823-8f74fa00-ede2-11e8-987b-81046726e58f.png)

**Comment by rajivshah3** [comment]
I'll keep this post updated with the progress I've made so far:

- [x] "Standard/Advanced" in settings menu Mode always shows Standard/Advanced instead of localized string, however the strings are shown correctly when using the switch to select between Standard and Advanced
- [x] "Mode updated" and "You have changed to Standard/Advanced mode" are not localized, no strings on crowdin
- [x] "Default/Classic/Mint/Electric/etc." theme names are not localized, although translated on crowdin
- [x] "Sending {{ amount }} (= {{ fiat_amount }}) from {{ account_name }} to {{ address }}" is not localized, no string on crowdin (appears when one needs to confirm sending iota to an address)
- [x] Status strings that are displayed above the progress bar during sending iota (like Preparing inputs, completing proof of work, etc.) are not localized
- [x] "Attaching address (counter) / (max number)" is not localized, no string on crowdin (progress indicator during snapshot transition)
- [x] "All" in dropdown menu
- [x] Update notification header on Trinity Desktop

**Comment by viossat** [comment]
Missing translations in most languages:

- `global.experimentalNodeExplanation`
- `global.youReceived`
- `global.youSent`
- `global.androidCopyPasteWarning`
- `global.confirm`
- `global.delete`
- `global.missingPermissionExplanation`
- `unitInfoModal.unitInfoExplanation`
- `unitInfoModal.unitSystem`
- `send.swipeToSend`
- `snapshotTransition.attachProgress`
- `progressSteps.transferComplete`
- `seedVault.retypeKey`
- `seedVault.seedVaultKeyExplanation`
- `paperWallet.print`
- `paperWallet.pleaseCheck`
- `paperWallet.wifiConfirmation`
- `paperWallet.printerConfirmation`
- `setPassword.anEncryptedCopy`
- `seedReentry.trinityWillNeverAskToReenter`
- `seedReentry.clipboardWarning`
- `seedReentry.clipboardWarningExplanation`
- `logoutConfirmationModal.aboutToLogOut`
- `login.whyBiometricDisabledExplanationPart1`
- `login.whyBiometricDisabledExplanationPart2`
- `transferConfirmation.fromAccount`
- `transferConfirmation.toAddress`
- `transferConfirmation.sendingAMessage`
- `transferConfirmation.sendingAnEmptyMessage`
- `history.pleaseWait`
- `saveYourSeed.whatIsAChecksum`
- `settings.account`
- `saveSeedConfirmation.iHaveBackedUp`
- `saveSeedConfirmation.reenterSeed`

**Comment by f-ben** [comment]
"swipe to confirm" not translated when creating a new seed (it is translated when initiating a new tx though)
![screenshot_20181223-220139](https://user-images.githubusercontent.com/2088471/50399487-1588b580-0780-11e9-84d8-e5e0e72241f5.jpg)

"Generate a new deposit address every time you wish to receive IOTA" - not translated and I couldnt find a string on crowdin
"Generate address" button is translated in crowdin
![newaddress](https://user-images.githubusercontent.com/2088471/50400393-a8c4e980-0786-11e9-87db-f31ce955b95b.jpeg)

Edit: holy cow the second picture is big :D dont know why, wasnt on purpose sorry
