### ISSUE TITLE
Allow copy-paste functionality for seeds

### ISSUE THREAD

**Issue by kstrafe** [iotaledger/trinity-wallet#566]
### Description
Ability to copy-paste seeds.

### Motivation
Because it's not in any way "better security" to not allow copy-pasting. In any case, I have to resort to `xdotool` to automatically type out the clipboard. Secondly, the clipboard is cleared after 45 seconds by `pass`, the standard unix password manager.

I understand that it may be useful for security unaware individuals, but for people who know what they're doing, it's just an annoying hurdle.

### Requirements
Allow either a toggle - or by default - to enable copy-pasting of seeds.

### Am I planning to do it myself with a PR?
No.

**Comment by f-ben** [comment]
Thats a security flaw which clearly will not pass any audit. Why not use a seedvault file?

**Comment by kstrafe** [comment]
How is it a security flaw?

I can't manage a seedvault file on linux because 1) I do not want a dependency on KeePass 2) I don't want to run a GUI application just to manage passwords.

**Comment by f-ben** [comment]
Maybe flaw is the wrong word. "Huge weakness" fits better I think. As someone who knows what he is doing I don´t need to tell you about keyloggers and similar software, you surely know that. The wallet has to protect users who do not know what they are doing and thus copy/paste is disabled. You´re better off cloning the repo and building your own version I guess.

**Comment by kstrafe** [comment]
It doesn't matter on a compromised device, you can log keys as well as the clipboard. There's no difference in that. I'm already using the native cache from first entering the codes (Perhaps this is in a seedvault, I don't know), but when porting your stuff to another machine it really doesn't matter if you type 'em out or paste it in.
Besides that, a compromised machine might as well leak your keyfiles and log keys to see the password used to decrypt them, or even dump Trinity's memory. So there's no difference.

**Comment by rajivshah3** [comment]
Copy/paste is currently disabled because the clipboard behavior in Electron causes the seed to remain in memory even after the garbage collector is triggered. Therefore, it would appear in a memory dump. Once we pinpoint what causes the seed to remain in memory and contribute an appropriate fix to Electron (if needed), we may be able to allow copy/paste.

**Comment by rajivshah3** [comment]
> I don't want to run a GUI application just to manage passwords.

You don't need a GUI application. I don't have a KeePass client. I just create the SeedVault from Trinity and save it somewhere safe. When I need it, Trinity will import and parse the KDBX. I don't need KeePass for that.

**Comment by kstrafe** [comment]
@rajivshah3 does electron implement its own clipboard functionality? I'm using the system clipboard (the one provided from the X windowing system to be specific). Or is electron's clipboard paste handler the cause of lingering seeds in memory?

>...just create the SeedVault from Trinity and save it somewhere safe.

While this is a solution, it's not preferred as I can't access the seed outside of using trinity (or KeePass), which is not ideal.

You state that "Trinity will import ...", can this be automated by setting a specific directory to read from? It's quite tedious to import each seed file manually.

**Comment by f-ben** [comment]
> You state that "Trinity will import ...", can this be automated by setting a specific directory to read from? It's quite tedious to import each seed file manually.

You only import your seedfiles once and then login with the password. No need to import the file everytime you open trinity.

> While this is a solution, it's not preferred as I can't access the seed outside of using trinity (or KeePass), which is not ideal.

Why would a regular user want to to this? Also you can keep your seed in your xdotool for everything else and use the seedvault file for trinity. This of course is a inconvinient way to handle the seed but your particular usecase (i dont get) is nothing a regular user worries about. I don´t think the trinity devs should lower security for 99% of users because 1% of users complain.

**Comment by cvarley100** [comment]
Copy paste is disabled as a security design decision. Users should use SeedVault for digital storage of seeds.

**Comment by alanrburns** [comment]
When will this stupidity be fixed?

**Comment by ghost** [comment]
Wow I can not believe how redundant this "security" feature is.

So a user has a seed.. they need to created a keepass file and then copy and paste it in the keepass file and then import it instead of just copy and pasting it directly in to the wallet app.

This is not solving any security issue because you still copy and paste your seed into the keepass file.

Maybe this is why IOTA has no value..LOL

**Comment by cvarley100** [comment]
@alanrburns We would prefer it if users generated their seed from within Trinity. A seed should never be copy pasted, nor should it really leave an encrypted file. We’re gradually trying to move towards best practices where the seed is abstracted altogether. Unfortunately not all users are as technically gifted as you.
