### ISSUE TITLE
Proof of Work progress indication

### ISSUE THREAD

**Issue by sloganking** [iotaledger/trinity-wallet#625]
### Description
Upon sending a transaction, show the number of transactions that have Proof of Work completed out of the total transactions in the bundle about to be broadcast. Similar to how the amount of addresses attached are now shown in snapshot transitioning.

### Motivation
This will assure progress is happening when Proof of Work is taking a while to complete. I.E. in large bundles.

### Requirements
replace generic "Completing Proof of Work" string 

![wcfqfn5](https://user-images.githubusercontent.com/16965931/48863785-94ad5700-ed98-11e8-8686-c74a5ecd5bc9.png)

with string that shows how many addresses have had their Proof of Work completed in the bundle about to be sent. Similar to what is currently done in snapshot transitioning on Trinity mobile.

![grppqh7](https://user-images.githubusercontent.com/16965931/48863793-9f67ec00-ed98-11e8-9ff3-821c0c7a6f72.png)

### Am I planning to do it myself with a PR?
No.

**Comment by rajivshah3** [comment]
We've changed the way that we do PoW for performance reasons. In the current alpha builds, we now pass the bundle, trunk and branch transaction, and min weight magnitude to a function and receive the nonces for all transactions in the bundle, instead of passing each transaction individually. Unfortunately, the new implementation doesn't allow us to implement this since we don't know how many transactions the PoW has been done for. If this changes, we might be able to revisit this
