### ISSUE TITLE
SeedVault timestamp in filename uses UTC instead of local time

### ISSUE THREAD

**Issue by UmbahaSpodPaha** [iotaledger/trinity-wallet#679]
### Bug description
Exported SeedVault filenames are mismatched by 1hour both for Desktop and Mobile.

**Android:**
![screenshot_20181130-215737_my files](https://user-images.githubusercontent.com/35224101/49314664-6a237280-f4eb-11e8-9a51-9eedb2ccefb7.jpg)

**PC:**
![time-mismatch-seedvault export](https://user-images.githubusercontent.com/35224101/49314665-6a237280-f4eb-11e8-8000-b1071e86446c.png)

### Environment Specs
Desktop: Windows 7 x64
Samsung Galaxy S9+: Android 8.0

- Trinity version:
0.4.3 desktop
0.5.1 (28) mobile

### Expected behaviour
Time should match in SeedVault filenames.

### Am I planning to do it myself with a PR?
No

**Comment by rajivshah3** [comment]
This isn't actually a bug. The code is doing what it's supposed to, but we probably shouldn't do it this way :trollface: 

https://github.com/iotaledger/trinity-wallet/blob/6bd9f69e140744fc3da9b54d0664f08e494663f3/src/mobile/src/ui/components/SeedVaultExportComponent.js#L140-L146

`toISOString()` will return the timestamp with UTC time, so it could be different from your local time. We should be using the local time though since we do that in other parts of the app
