### ISSUE TITLE
blank screen on first run

### ISSUE THREAD

**Issue by mostar** [iotaledger/trinity-wallet#964]
### Bug description
blank screen on first run

### Environment Specs
What device are you running Trinity on?

- Manufacturer: 
- Model: 
- OS version: ubuntu 14.04

What build of Trinity are you running? Please provide the full version (you can find it in Settings > About Trinity).

- Trinity version: 
Trinity Desktop v0.4.6

### Steps To Reproduce
1. chmod 755 trinity-desktop-0.4.6.AppImage
2. ./trinity-desktop-0.4.6.AppImage

### Expected behaviour
see some menus

### Actual behaviour
blank screen

### Errors
none

**Comment by sloganking** [comment]
@mostar Could you provide any pictures of what "blank screen" is? Does the Trinity window open and only show the background color or something else?

**Comment by mostar** [comment]
Trinity window open and only show the background color

**Comment by rihardsgravis** [comment]
@mostar Is this still reproducible on `0.5.0`?

**Comment by alangrainger** [comment]
This issue happens on Windows after coming from a much older version without uninstalling.

I imagine the fix is essentially the same for Ubuntu.

On Windows you need to go to the %AppData% directory and delete the 'trinity' subfolder. Then install the new version and everything is peachy.

Give that a go on Ubuntu, but just replace %AppData% with whatever the equivalent is.

**Comment by rihardsgravis** [comment]
Blank screen issue fixed in #1549 . If the problem reappears with a specific error, a new issue should be opened.
